# Tomcat
server:
  #tomcat:
   # uri-encoding: UTF-8
   # max-threads: 1000
   # min-spare-threads: 30
  #port: 443
  #ssl:
   # key-store: classpath:1955000__zjysx.cn.pfx
   # key-store-password: 5j83o88P
   # key-store-type: PKCS12
  #connection-timeout: 5000ms
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  #messages:
   # encoding: UTF-8
   # basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
   # thymeleaf 
  thymeleaf:
    prefix:classpath:/templates/
    check-template-location:true
    suffix:.html
    encoding:UTF-8
    content-type:text/html
    mode:HTML5
    cache:false
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.silverTrain.schedule.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
#      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

 

